# Generated by Django 5.2 on 2025-05-30 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.FloatField()),
                ("percentage", models.FloatField(blank=True, null=True)),
                ("letter_grade", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "student_course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade",
                        to="courses.studentcourse",
                    ),
                ),
            ],
        ),
    ]
