# Generated by Django 5.2 on 2025-05-30 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("grades", "0002_gradesheet_studentgrade_delete_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gradesheet",
            name="created_at",
        ),
        migrations.AddField(
            model_name="studentgrade",
            name="letter_grade",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="studentgrade",
            name="percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="gradesheet",
            name="course",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="courses.course"
            ),
        ),
        migrations.AlterField(
            model_name="studentgrade",
            name="score",
            field=models.FloatField(default=0),
        ),
    ]
