# Generated by Django 5.2 on 2025-05-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0003_remove_gradesheet_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradesheet",
            name="full_score",
            field=models.FloatField(default=100),
        ),
    ]
