# Generated by Django 5.2 on 2025-05-30 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_doctor_is_admin_doctor"),
        ("grades", "0004_gradesheet_full_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradesheet",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.doctor",
            ),
        ),
    ]
