# Generated by Django 5.2 on 2025-05-22 18:12

import dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_doctor_structure_student_structure"),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dash",
            name="student",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.student",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dash",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=dashboard.models.image_upload
            ),
        ),
    ]
