# Generated by Django 5.2 on 2025-04-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="phone_number",
            new_name="mobile",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="doctor",
            name="mobile",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
