# Generated by Django 5.2 on 2025-05-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_doctor_structure_student_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_admin_doctor",
            field=models.BooleanField(default=False),
        ),
    ]
