# Generated by Django 5.2 on 2025-05-09 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_doctor_structure_student_structure"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("AI", "Artificial Intelligence"),
                            ("DATA", "Data Sceince"),
                            ("CYBER", "Cyber Security"),
                            ("AUTOTRONICS", "Autotronics"),
                            ("MECHATRONICS", "Mechatronics"),
                            ("GARMENT_MANUFACTURING", "Garment Manufacturing"),
                            ("CONTROL_SYSTEMS", "Control Systems"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        choices=[
                            ("First", "First Year"),
                            ("Second", "Second Year"),
                            ("Third", "Third Year"),
                            ("Fourth", "Fourth Year"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("First", "First Semester"),
                            ("Second", "Second Semester"),
                        ],
                        max_length=6,
                    ),
                ),
                ("drive_link", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.doctor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                    ),
                ),
            ],
        ),
    ]
