# Generated by Django 5.2 on 2025-05-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("AI", "Artificial Intelligence"),
                            ("DATA", "Data Sceince"),
                            ("CYBER", "Cyber Security"),
                            ("AUTOTRONICS", "Autotronics"),
                            ("MECHATRONICS", "Mechatronics"),
                            ("GARMENT_MANUFACTURING", "Garment Manufacturing"),
                            ("CONTROL_SYSTEMS", "Control Systems"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("First", "الفرقة الأولى"),
                            ("Second", "الفرقة الثانية"),
                            ("Third", "الفرقة الثالثة"),
                            ("Fourth", "الفرقة الرابعة"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[("First", "الترم الأول"), ("Second", "الترم الثاني")],
                        max_length=6,
                    ),
                ),
            ],
        ),
    ]
