# Generated by Django 5.2 on 2025-05-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structure", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentstructure",
            name="semester",
            field=models.CharField(
                choices=[("First", "First Semester"), ("Second", "Second Semester")],
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="studentstructure",
            name="year",
            field=models.CharField(
                choices=[
                    ("First", "First Year"),
                    ("Second", "Second Year"),
                    ("Third", "Third Year"),
                    ("Fourth", "Fourth Year"),
                ],
                max_length=6,
            ),
        ),
    ]
