# Generated by Django 5.2 on 2025-05-10 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcodesession",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
